### ISSUE TITLE
ADD LICENSE.MD

### ISSUE THREAD

**Issue by victorhugorch** [darthdevz/xplainshell-bot#2]
Qual melhor licença pro projeto? 

Alguém se disponibiliza a adicionar o arquivo e o link no README.md?

**Comment by HeavenVolkoff** [comment]
Por mim MPL 2.0 / GPL 3.0 / LGPL 3.0

**Comment by HeavenVolkoff** [comment]
Adicionaram a GPL 3.0, então vou fechar essa issue
